#!/usr/bin/env bash
# cloud_watchers.sh — Start AI Employee watchers on the cloud VM via PM2
#
# The orchestrator.py manages all individual watcher subprocesses with
# circuit breakers. PM2 keeps the orchestrator itself alive across reboots.
#
# Usage:
#   ./deployment/cloud_watchers.sh          # start / restart
#   ./deployment/cloud_watchers.sh stop     # stop all
#   ./deployment/cloud_watchers.sh logs     # tail live logs
#   ./deployment/cloud_watchers.sh status   # show PM2 process table

set -euo pipefail
IFS=$'\n\t'

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
info() { echo -e "${GREEN}[watchers]${NC} $*"; }
warn() { echo -e "${YELLOW}[warn]${NC}  $*"; }
die()  { echo -e "${RED}[error]${NC} $*" >&2; exit 1; }

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VENV_PYTHON="$PROJECT_ROOT/.venv/bin/python"
APP_NAME="ai-employee-orchestrator"
ECOSYSTEM="$PROJECT_ROOT/deployment/ecosystem.config.cjs"

COMMAND="${1:-start}"

# ── Pre-flight checks ─────────────────────────────────────────────────────────
command -v pm2 &>/dev/null || die "PM2 not found. Run: sudo npm install -g pm2"
[ -f "$VENV_PYTHON" ] || die ".venv not found. Run: ./deployment/cloud_setup.sh"
[ -f "$PROJECT_ROOT/.env" ] || die ".env not found. Copy .env.example to .env and fill in values."
[ -f "$PROJECT_ROOT/scheduler/orchestrator.py" ] || die "orchestrator.py not found."

# ── Browser watchers: check for display ──────────────────────────────────────
check_display() {
    if [ -z "${DISPLAY:-}" ] && [ -z "${XVFB_RUN:-}" ]; then
        warn "No DISPLAY env var set."
        warn "Browser-based watchers (LinkedIn, Facebook, Instagram, Twitter)"
        warn "need a virtual display on a headless server."
        warn "Options:"
        warn "  1. Set DISPLAY=:99 and start Xvfb: Xvfb :99 -screen 0 1280x1024x24 &"
        warn "  2. Or run this script with: XVFB_RUN=1 ./deployment/cloud_watchers.sh"
        warn "  3. Or add 'headless: true' to the Playwright watcher launch options."
        warn "Continuing — non-browser watchers (Gmail, FileSystem) will work fine."
    fi
}

# ── Generate PM2 ecosystem config ─────────────────────────────────────────────
write_ecosystem() {
    # Resolve VAULT_PATH from .env, default to ./vault
    VAULT_PATH=$(grep -E '^VAULT_PATH=' "$PROJECT_ROOT/.env" 2>/dev/null \
                 | cut -d= -f2 | tr -d '"' | tr -d "'" || echo "./vault")
    [ -z "$VAULT_PATH" ] && VAULT_PATH="./vault"

    cat > "$ECOSYSTEM" <<EOF
// PM2 Ecosystem Config — AI Employee (Platinum Tier)
// Auto-generated by cloud_watchers.sh — do not edit manually
// Re-run ./deployment/cloud_watchers.sh to regenerate.

module.exports = {
  apps: [
    {
      name: "$APP_NAME",
      script: "$VENV_PYTHON",
      args: "scheduler/orchestrator.py --vault $VAULT_PATH",
      cwd: "$PROJECT_ROOT",
      interpreter: "none",          // script IS the interpreter
      restart_delay: 5000,          // 5s between PM2-level restarts
      max_restarts: 10,             // PM2 gives up after 10 rapid restarts
      min_uptime: "30s",            // must survive 30s to count as "stable"
      exp_backoff_restart_delay: 100,
      watch: false,                 // orchestrator manages its own children
      env: {
        PYTHONUNBUFFERED: "1",
        VAULT_PATH: "$VAULT_PATH",
      },
      env_file: "$PROJECT_ROOT/.env",
      log_date_format: "YYYY-MM-DDTHH:mm:ssZ",
      out_file: "$PROJECT_ROOT/vault/Logs/pm2-out.log",
      error_file: "$PROJECT_ROOT/vault/Logs/pm2-err.log",
      merge_logs: true,
    }
  ]
};
EOF
    info "Ecosystem config written → $ECOSYSTEM"
}

# ── Commands ──────────────────────────────────────────────────────────────────
case "$COMMAND" in

  start)
    check_display
    write_ecosystem

    if pm2 describe "$APP_NAME" &>/dev/null; then
        info "Reloading existing PM2 process: $APP_NAME"
        pm2 reload "$ECOSYSTEM" --update-env
    else
        info "Starting $APP_NAME via PM2..."
        pm2 start "$ECOSYSTEM"
    fi

    pm2 save
    info "PM2 config saved (will survive reboot)"

    # Set up PM2 startup script (only needs to run once, may prompt for sudo)
    if ! pm2 startup 2>&1 | grep -q "already"; then
        warn "Run the startup command shown above with sudo to enable auto-start on reboot."
    fi

    echo ""
    info "Watchers running. Useful commands:"
    echo "  pm2 status                            # process health"
    echo "  pm2 logs $APP_NAME        # live logs"
    echo "  pm2 monit                             # interactive dashboard"
    echo "  ./deployment/cloud_watchers.sh stop   # stop all"
    ;;

  stop)
    info "Stopping $APP_NAME..."
    pm2 stop "$APP_NAME" 2>/dev/null || warn "Process not running"
    pm2 delete "$APP_NAME" 2>/dev/null || true
    pm2 save
    info "Stopped"
    ;;

  logs)
    exec pm2 logs "$APP_NAME" --lines 100
    ;;

  status)
    pm2 status
    ;;

  restart)
    info "Restarting $APP_NAME..."
    pm2 restart "$APP_NAME"
    ;;

  *)
    die "Unknown command: $COMMAND\nUsage: cloud_watchers.sh [start|stop|restart|logs|status]"
    ;;

esac
